language: c

compiler:
        - gcc
        - clang

os:
        - linux
        - osx
        - bsd
        - solaris

before_install:
        - echo $LANG
        - echo $LC_ALL

install:
        - bash autogen.sh

before_script:
        - ./configure

script:
        - make

after_success:
        - make tests


